services:
  app:
    container_name: vcs_tech_app
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/app
    entrypoint: >
      bash -c "chown -R chuongvq:chuongvq /var/www/html/app && exec php-fpm"
    networks:
      - app_network

  nginx:
    image: nginx:1.23.1
    container_name: vcs_tech_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .docker/nginx/config/app.conf:/etc/nginx/conf.d/app.conf
      - .docker/nginx/logs:/var/log/nginx
      - .docker/ssl:/etc/nginx/ssl:cached
      - ./src:/var/www/html/app
    depends_on: 
      - app
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: vcs_tech_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tech_shop
      MYSQL_USER: app_user
      MYSQL_PASSWORD: techshop123456
    ports:
      - "3309:3306"
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin
    container_name: vcs_tech_phpmyadmin
    ports:
      - "8282:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=64M
    networks:
      - app_network

networks:
  app_network: